site_name: pico-jxglib
site_description: A collection of libraries and tools for Raspberry Pi Pico, including a powerful shell and various utilities to enhance your development experience.
copyright: "2025-2026, ypsitau"
repo_url: https://github.com/ypsitau/pico-jxglib
repo_name: ypsitau/pico-jxglib

nav:
    - Home: index.md
    - Shell:
        - Overview: shell/index.md
        - Basic Commands: shell/basic/index.md
        - File System:
            - Overview: shell/filesystem/index.md
            - File Operating Commands: shell/filesystem/file-operating-commands/index.md
            - RTC (Real Time Clock) Support: shell/filesystem/rtc/index.md
            - SD Card Support: shell/filesystem/sdcard/index.md
        - Peripheral:
            - GPIO: shell/peripheral/gpio/index.md
            - PWM: shell/peripheral/pwm/index.md
            - I2C: shell/peripheral/i2c/index.md
            - SPI: shell/peripheral/spi/index.md
            - UART: shell/peripheral/uart/index.md
        - Device:
            - Built-in LED: shell/device/builtin-led/index.md
            - RTC (Real Time Clock): shell/device/rtc/index.md
            - SD Card: shell/device/sdcard/index.md
        - Network:
            - Overview: shell/network/index.md
            - Wi-Fi Connection: shell/network/wifi/index.md
            - Network Utilities: shell/network/network-utilities/index.md
            - Telnet Server: shell/network/telnet-server/index.md
        - Logic Analyzer:
            - Overview: shell/logic-analyzer/index.md
            - Data Sampling: shell/logic-analyzer/text/data-sampling.md
            - Text Mode:
                - Waveform on Console: shell/logic-analyzer/text/waveform.md
                - Protocol Analysis on Console: shell/logic-analyzer/text/protocol-analysis.md
            - PulseView:
                - Setup Pulseview: shell/logic-analyzer/pulseview/setup-pulseview.md
        - Display:
            - WS2812: shell/display/ws2812/index.md
        - Camera:
            - OV7670: shell/camera/ov7670/index.md
    - Library APIs:
        - Overview: library/index.md
        - LABOPlatform: library/labo-platform/index.md
        - Shell:
            - Overview: library/shell/index.md
            - Connectability:
                - Stdio: library/shell/shell-with-stdio.md
                - TFT LCD + USB Keyboard: library/shell/shell-with-tftlcd-usbkey.md
                - OLED + USB Keyboard: library/shell/shell-with-oled-usbkey.md
            - Custom Commands: library/shell/custom-commands.md
        - File System:
            - Overview: library/filesystem/index.md
            - Internal Flash Memory:
                - About Flash Memory: library/filesystem/fs-flash.md
                - LittleFS: library/filesystem/fs-flash-lfs.md
                - FAT: library/filesystem/fs-flash-fat.md
                - Multiple Drives: library/filesystem/fs-flash-multi.md
            - SD Card: library/filesystem/sdcard.md
            - USB Storage: library/filesystem/usb-storage.md
            - API Reference: library/filesystem/api-reference.md
        - Peripheral:
            - GPIO: library/peripheral/gpio/index.md
            - PWM: library/peripheral/pwm/index.md
            - I2C: library/peripheral/i2c/index.md
            - SPI: library/peripheral/spi/index.md
            - UART: library/peripheral/uart/index.md
        - Device:
            - Built-in LED: library/device/builtin-led/index.md
            - RTC (Real Time Clock): library/device/rtc/index.md
        - Terminal:
            - Overview: library/terminal/index.md
            - Connectability:
                - TFT LCD: library/terminal/terminal-with-tftlcd.md
                - OLED: library/terminal/terminal-with-oled.md
            - Working with LVGL: library/terminal/terminal-and-lvgl.md
            - Multiple Terminals: library/terminal/terminal-multiple.md
        - Display:
            - Overview: library/display/index.md
            - TFT LCD:
                - Overview: library/display/tft-lcd/index.md
                - Sample Program:
                    - Drawing: library/display/tft-lcd/sample-drawing.md
                    - Multiple LCDs: library/display/tft-lcd/sample-multi.md
            - OLED:
                - Overview: library/display/oled/index.md
            - WS2812:
                - Overview: library/display/ws2812/index.md
        - Keyboard:
            - Overview: library/keyboard/index.md
            - USB Keyboard: library/keyboard/usb-keyboard.md
            - GPIO Keyboard: library/keyboard/gpio-keyboard.md
            - GPIO Keyboard Matrix: library/keyboard/gpio-keyboard-matrix.md
        - USB Host:
            - Overview: library/usbhost/index.md
            - Keyboard & Mouse: library/usbhost/keyboard-mouse/index.md
            - Game Pad: library/usbhost/gamepad/index.md
        - USB Client:
            - Overview: library/usbclient/index.md
        - Toolkits:
            - LVGL:
                - Overview: library/toolkit/lvgl/index.md
            - Tiny ML:
                - Overview: library/toolkit/tiny-ml/index.md
    - Applications:
        - Overview: applications/index.md
        - Character Recognizer: applications/character-recognizer/index.md
    - Development Environment:
        - Overview: development/index.md
        - Getting Started with Pico SDK: development/pico-sdk/index.md
        - Quick Guide to CMake: development/cmake/index.md

plugins:
    - include-markdown

theme:
    name: material
    icon:
        logo: material/chip
        repo: fontawesome/brands/github
    language: en
    palette:
        primary: indigo
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        #- navigation.expand
        - navigation.path
        - navigation.top
        - navigation.footer
        - content.code.copy

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets:
        base_path: ["docs", "src"]
        check_paths: true
    - admonition
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - attr_list
    - md_in_html
    - def_list
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
    analytics:
        provider: google
        property: G-RR9PCYFTE8

extra_javascript:
    - javascripts/mathjax.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - stylesheets/extra.css

#exclude_docs: include/*
