site_name: pico-jxglib
site_description: A collection of libraries and tools for Raspberry Pi Pico, including a powerful shell and various utilities to enhance your development experience.
copyright: "2025-2026, ypsitau"
nav:
  - Home: index.md
  - Shell:
      - Shell: shell/index.md
      - File Operations: shell/file-operations/index.md
      - Logic Analyzer:
          - Text Mode: shell/la-text/index.md
          - PulseView: shell/la-pulseview/index.md
      - GPIO: shell/gpio/index.md
      - I2C: shell/i2c/index.md
      - SPI: shell/spi/index.md
      - UART: shell/uart/index.md
  - Library:
      - Library: library/index.md
theme:
  name: material
  icon:
    logo: material/chip
  language: en
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  