//==============================================================================
// jxglib/KeyCode.h
// https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
//==============================================================================
#ifndef PICO_JXGLIB_KEYCODE_H
#define PICO_JXGLIB_KEYCODE_H
#include "pico/stdlib.h"

namespace jxglib {

//------------------------------------------------------------------------------
// KeyCode
//------------------------------------------------------------------------------
static const uint8_t VK_LBUTTON				= 0x01;
static const uint8_t VK_RBUTTON				= 0x02;
static const uint8_t VK_CANCEL				= 0x03;
static const uint8_t VK_MBUTTON				= 0x04;
static const uint8_t VK_XBUTTON1			= 0x05;
static const uint8_t VK_XBUTTON2			= 0x06;
static const uint8_t VK_BACK				= 0x08;
static const uint8_t VK_TAB					= 0x09;
static const uint8_t VK_CLEAR				= 0x0c;
static const uint8_t VK_RETURN				= 0x0d;
static const uint8_t VK_SHIFT				= 0x10;
static const uint8_t VK_CONTROL				= 0x11;
static const uint8_t VK_MENU				= 0x12;
static const uint8_t VK_PAUSE				= 0x13;
static const uint8_t VK_CAPITAL				= 0x14;
static const uint8_t VK_KANA				= 0x15;
static const uint8_t VK_HANGUL				= 0x15;
static const uint8_t VK_IME_ON				= 0x16;
static const uint8_t VK_JUNJA				= 0x17;
static const uint8_t VK_FINAL				= 0x18;
static const uint8_t VK_KANJI				= 0x19;
static const uint8_t VK_ESCAPE				= 0x1b;
static const uint8_t VK_CONVERT				= 0x1c;
static const uint8_t VK_NONCONVERT			= 0x1d;
static const uint8_t VK_ACCEPT				= 0x1e;
static const uint8_t VK_MODECHANGE			= 0x1f;
static const uint8_t VK_SPACE				= 0x20;
static const uint8_t VK_PRIOR				= 0x21;
static const uint8_t VK_NEXT				= 0x22;
static const uint8_t VK_END					= 0x23;
static const uint8_t VK_HOME				= 0x24;
static const uint8_t VK_LEFT				= 0x25;
static const uint8_t VK_UP					= 0x26;
static const uint8_t VK_RIGHT				= 0x27;
static const uint8_t VK_DOWN				= 0x28;
static const uint8_t VK_SELECT				= 0x29;
static const uint8_t VK_PRINT				= 0x2a;
static const uint8_t VK_EXECUTE				= 0x2b;
static const uint8_t VK_SNAPSHOT			= 0x2c;
static const uint8_t VK_INSERT				= 0x2d;
static const uint8_t VK_DELETE				= 0x2e;
static const uint8_t VK_HELP				= 0x2f;
static const uint8_t VK_0                   = '0';
static const uint8_t VK_1                   = '1';
static const uint8_t VK_2                   = '2';
static const uint8_t VK_3                   = '3';
static const uint8_t VK_4                   = '4';
static const uint8_t VK_5                   = '5';
static const uint8_t VK_6                   = '6';
static const uint8_t VK_7                   = '7';
static const uint8_t VK_8                   = '8';
static const uint8_t VK_9                   = '9';
static const uint8_t VK_A                   = 'A';
static const uint8_t VK_B                   = 'B';
static const uint8_t VK_C                   = 'C';
static const uint8_t VK_D                   = 'D';
static const uint8_t VK_E                   = 'E';
static const uint8_t VK_F                   = 'F';
static const uint8_t VK_G                   = 'G';
static const uint8_t VK_H                   = 'H';
static const uint8_t VK_I                   = 'I';
static const uint8_t VK_J                   = 'J';
static const uint8_t VK_K                   = 'K';
static const uint8_t VK_L                   = 'L';
static const uint8_t VK_M                   = 'M';
static const uint8_t VK_N                   = 'N';
static const uint8_t VK_O                   = 'O';
static const uint8_t VK_P                   = 'P';
static const uint8_t VK_Q                   = 'Q';
static const uint8_t VK_R                   = 'R';
static const uint8_t VK_S                   = 'S';
static const uint8_t VK_T                   = 'T';
static const uint8_t VK_U                   = 'U';
static const uint8_t VK_V                   = 'V';
static const uint8_t VK_W                   = 'W';
static const uint8_t VK_X                   = 'X';
static const uint8_t VK_Y                   = 'Y';
static const uint8_t VK_Z                   = 'Z';
static const uint8_t VK_LWIN				= 0x5b;
static const uint8_t VK_RWIN				= 0x5c;
static const uint8_t VK_APPS				= 0x5d;
static const uint8_t VK_SLEEP				= 0x5f;
static const uint8_t VK_NUMPAD0				= 0x60;
static const uint8_t VK_NUMPAD1				= 0x61;
static const uint8_t VK_NUMPAD2				= 0x62;
static const uint8_t VK_NUMPAD3				= 0x63;
static const uint8_t VK_NUMPAD4				= 0x64;
static const uint8_t VK_NUMPAD5				= 0x65;
static const uint8_t VK_NUMPAD6				= 0x66;
static const uint8_t VK_NUMPAD7				= 0x67;
static const uint8_t VK_NUMPAD8				= 0x68;
static const uint8_t VK_NUMPAD9				= 0x69;
static const uint8_t VK_MULTIPLY			= 0x6a;
static const uint8_t VK_ADD					= 0x6b;
static const uint8_t VK_SEPARATOR			= 0x6c;
static const uint8_t VK_SUBTRACT			= 0x6d;
static const uint8_t VK_DECIMAL				= 0x6e;
static const uint8_t VK_DIVIDE				= 0x6f;
static const uint8_t VK_F1					= 0x70;
static const uint8_t VK_F2					= 0x71;
static const uint8_t VK_F3					= 0x72;
static const uint8_t VK_F4					= 0x73;
static const uint8_t VK_F5					= 0x74;
static const uint8_t VK_F6					= 0x75;
static const uint8_t VK_F7					= 0x76;
static const uint8_t VK_F8					= 0x77;
static const uint8_t VK_F9					= 0x78;
static const uint8_t VK_F10					= 0x79;
static const uint8_t VK_F11					= 0x7a;
static const uint8_t VK_F12					= 0x7b;
static const uint8_t VK_F13					= 0x7c;
static const uint8_t VK_F14					= 0x7d;
static const uint8_t VK_F15					= 0x7e;
static const uint8_t VK_F16					= 0x7f;
static const uint8_t VK_F17					= 0x80;
static const uint8_t VK_F18					= 0x81;
static const uint8_t VK_F19					= 0x82;
static const uint8_t VK_F20					= 0x83;
static const uint8_t VK_F21					= 0x84;
static const uint8_t VK_F22					= 0x85;
static const uint8_t VK_F23					= 0x86;
static const uint8_t VK_F24					= 0x87;
static const uint8_t VK_NUMLOCK				= 0x90;
static const uint8_t VK_SCROLL				= 0x91;
static const uint8_t VK_LSHIFT				= 0xa0;
static const uint8_t VK_RSHIFT				= 0xa1;
static const uint8_t VK_LCONTROL			= 0xa2;
static const uint8_t VK_RCONTROL			= 0xa3;
static const uint8_t VK_LMENU				= 0xa4;
static const uint8_t VK_RMENU				= 0xa5;
static const uint8_t VK_BROWSER_BACK		= 0xa6;
static const uint8_t VK_BROWSER_FORWARD		= 0xa7;
static const uint8_t VK_BROWSER_REFRESH		= 0xa8;
static const uint8_t VK_BROWSER_STOP		= 0xa9;
static const uint8_t VK_BROWSER_SEARCH		= 0xaa;
static const uint8_t VK_BROWSER_FAVORITES	= 0xab;
static const uint8_t VK_BROWSER_HOME		= 0xac;
static const uint8_t VK_VOLUME_MUTE			= 0xad;
static const uint8_t VK_VOLUME_DOWN			= 0xae;
static const uint8_t VK_VOLUME_UP			= 0xaf;
static const uint8_t VK_MEDIA_NEXT_TRACK	= 0xb0;
static const uint8_t VK_MEDIA_PREV_TRACK	= 0xb1;
static const uint8_t VK_MEDIA_STOP			= 0xb2;
static const uint8_t VK_MEDIA_PLAY_PAUSE	= 0xb3;
static const uint8_t VK_LAUNCH_MAIL			= 0xb4;
static const uint8_t VK_LAUNCH_MEDIA_SELECT	= 0xb5;
static const uint8_t VK_LAUNCH_APP1			= 0xb6;
static const uint8_t VK_LAUNCH_APP2			= 0xb7;
static const uint8_t VK_OEM_1				= 0xba;
static const uint8_t VK_OEM_PLUS			= 0xbb;
static const uint8_t VK_OEM_COMMA			= 0xbc;
static const uint8_t VK_OEM_MINUS			= 0xbd;
static const uint8_t VK_OEM_PERIOD			= 0xbe;
static const uint8_t VK_OEM_2				= 0xbf;
static const uint8_t VK_OEM_3				= 0xc0;
static const uint8_t VK_OEM_4				= 0xdb;
static const uint8_t VK_OEM_5				= 0xdc;
static const uint8_t VK_OEM_6				= 0xdd;
static const uint8_t VK_OEM_7				= 0xde;
static const uint8_t VK_OEM_8				= 0xdf;
static const uint8_t VK_OEM_102				= 0xe2;
static const uint8_t VK_PROCESSKEY			= 0xe5;
static const uint8_t VK_PACKET				= 0xe7;
static const uint8_t VK_ATTN				= 0xf6;
static const uint8_t VK_CRSEL				= 0xf7;
static const uint8_t VK_EXSEL				= 0xf8;
static const uint8_t VK_EREOF				= 0xf9;
static const uint8_t VK_PLAY				= 0xfa;
static const uint8_t VK_ZOOM				= 0xfb;
static const uint8_t VK_NONAME				= 0xfc;
static const uint8_t VK_PA1					= 0xfd;
static const uint8_t VK_OEM_CLEAR			= 0xfe;

const char* GetKeyCodeName(uint8_t keyCode);

}

#endif
